export const BUY_TICKET_REQUEST = "BUY_TICKET_REQUEST";
export const BUY_TICKET_SUCCESS = "BUY_TICKET_SUCCESS";
export const BUY_TICKET_FAILED = "BUY_TICKET_FAILED";

export const REFRESH_STATE_TICKET = "REFRESH_STATE_TICKET";
export const CHOSING_TICKETS = "CHOSING_TICKETS";
