export const BOOKING_MOVIE_PAGE_REQUEST = "BOOKING_MOVIE_PAGE_REQUEST";
export const BOOKING_MOVIE_PAGE_SUCCESS = "BOOKING_MOVIE_PAGE_SUCCESS";
export const BOOKING_MOVIE_PAGE_FAILED = "BOOKING_MOVIE_PAGE_FAILED";
