export const DETAIL_MOVIE_REQUEST = "DETAIL_MOVIE_REQUEST";

export const DETAIL_MOVIE_SUCCESS = "DETAIL_MOVIE_SUCCESS";

export const DETAIL_MOVIE_FAILED = "DETAIL_MOVIE_FAILED";

export const SELECT_DAY = "SELECT_DAY";
