export const LIST_HE_THONG_RAP_REQUEST = "LIST_HE_THONG_RAP_REQUEST";
export const LIST_HE_THONG_RAP_SUCCESS = "LIST_HE_THONG_RAP_SUCCESS";
export const LIST_HE_THONG_RAP_FAILED = "LIST_HE_THONG_RAP_FAILED";

export const LAY_THONG_TIN_LICH_CHIEU_REQUEST =
  "LAY_THONG_TIN_LICH_CHIEU_REQUEST";
export const LAY_THONG_TIN_LICH_CHIEU_SUCCESS =
  "LAY_THONG_TIN_LICH_CHIEU_SUCCESS";
export const LAY_THONG_TIN_LICH_CHIEU_FAILED =
  "LAY_THONG_TIN_LICH_CHIEU_FAILED";
